---
- name: Create config directory
  ansible.builtin.file:
    path: /opt/app-loki/config
    state: directory
    owner: docker_files
    group: docker_files
    mode: 0755

- name: Copy files
  ansible.builtin.copy:
    src: loki-config.yml
    dest: /opt/app-loki/config/loki-config.yml
    owner: docker_files
    group: docker_files
    mode: 0644

- name: Ensure grafana/loki image is pulled
  community.docker.docker_image:
    name: docker.io/grafana/loki:2.6.1
    source: pull
    force_source: yes
  register: pulled

- name: Remove loki container
  community.docker.docker_container:
    name: loki
    state: absent
  when: pulled.changed

- name: Get infos on loki container
  community.docker.docker_container_info:
    name: loki
  register: result

- name: Create loki container
  ansible.builtin.shell: |
    docker run -d \
    --name=loki \
    -v /opt/app-loki/config:/mnt/config:Z \
    --network=app-network \
    --restart unless-stopped \
    docker.io/grafana/loki:2.6.1 \
    -config.file=/mnt/config/loki-config.yml
  when: 
    pulled.changed
    or
    result.exists == false
